# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 390a6ab20b5b6b85fe2bf9f6709d3c2166cebd595608f3937751ddffd5af69d05c93e22370ba92e9eed61aa2b4103f9fe7e4cd8d23e758de96c02b61c54b135d

test:
  secret_key_base: b8a97a7f160932f3e5267fbce609f8cbf494020aed3468588b496c5565b4e9168be942b0357b29fd11544b0a785b0662b57ff7cc5c1bd5eb380a123b4275cfe9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
